### ISSUE TITLE
de.envite.greenbpm.api.carbonawaresdk.ApiException: Message: Forbidden

### ISSUE THREAD

**Issue by RodrigoCarlstrom** [envite-consulting/camunda-carbon-reductor#91]
Hello friends of Camunda and the planet, I hope this message finds you well!

I follow these documents step by step:
[camunda-carbon-reductor-c8](https://github.com/envite-consulting/camunda-carbon-reductor/tree/main/camunda-carbon-reductor-c8)
AND
[api-carbon-aware](https://github.com/envite-consulting/camunda-carbon-reductor/blob/main/api/api-carbon-aware/README.md)

I was able to create the user on watttime.org and generate the token through login.

I made the changes indicated in docker-compose as follows:
[docker-compose.yaml](https://github.com/envite-consulting/camunda-carbon-reductor/blob/main/camunda-carbon-reductor-c8/docker-compose.yaml)

I uploaded docker with docker-compose up and tested:
http://localhost:8090/emissions/forecasts/current?location=westus
It's working correctly.

However, the connector is giving an incident:
`Expected to throw an error event with the code 'carbon-reductor-error' with message 'Could not query API to get infos about future emissions', but it was not caught. No error events are available in the scope.`

In the camunda-8-carbon-reductor-connector docker console:

```
2023-10-14 10:29:11 2023-10-14 13:29:11.223 ERROR 1 --- [pool-1-thread-1] d.e.g.c.c.a.w.CarbonAwareSdkClient : Error when calling the API for the optimalForecastUntil
2023-10-14 10:29:11
2023-10-14 10:29:11 de.envite.greenbpm.api.carbonawaresdk.ApiException: Message: Forbidden
2023-10-14 10:29:11 HTTP response code: 403
2023-10-14 10:29:11 HTTP response body: {"title":"WattTimeClientHttpException","status":403,"detail":"Error requesting forecast?ba=UK","traceId":"00- 304b5b25e57e4c7b918e9dba41e166c2-f751c3da54859e37-01","errors":{}}
2023-10-14 10:29:11 HTTP response headers: {content-type=[application/problem+json; charset=utf-8], date=[Sat, 14 Oct 2023 13:29:10 GMT], server=[Kestrel], transfer-encoding=[chunked]}
2023-10-14 10:29:11 at de.envite.greenbpm.api.carbonawaresdk.ApiClient.handleResponse(ApiClient.java:1115) ~[api-carbon-aware-2.0.2.jar!/:2.0.2 ]
2023-10-14 10:29:11 at de.envite.greenbpm.api.carbonawaresdk.ApiClient.execute(ApiClient.java:1028) ~[api-carbon-aware-2.0.2.jar!/:2.0.2 ]
2023-10-14 10:29:11 at de.envite.greenbpm.api.carbonawaresdk.api.CarbonAwareApi.getCurrentForecastDataWithHttpInfo(CarbonAwareApi.java:790) ~[api-carbon-aware-2.0.2.jar!/:2.0 .two]
2023-10-14 10:29:11 at de.envite.greenbpm.carbonreductor.core.adapter.watttime.CarbonAwareSdkClient.getOptimalForecastUntil(CarbonAwareSdkClient.java:37) ~[carbon-reductor-core-2.0.2.jar!/ :2.0.2]
2023-10-14 10:29:11 at de.envite.greenbpm.carbonreductor.core.adapter.watttime.CarbonAwareSdkClient.getEmissionTimeframe(CarbonAwareSdkClient.java:28) ~[carbon-reductor-core-2.0.2.jar!/ :2.0.2]
2023-10-14 10:29:11 at de.envite.greenbpm.carbonreductor.core.domain.service.DelayCalculatorService.calculateDelay(DelayCalculatorService.java:39) ~[carbon-reductor-core-2.0.2.jar!/ :2.0.2]
2023-10-14 10:29:11 at de.envite.greenbpm.carbonreductorconnector.adapter.in.zeebe.CarbonReductorWorker.execute(CarbonReductorWorker.java:45) ~[classes!/:2.0.2]
2023-10-14 10:29:11 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
2023-10-14 10:29:11 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
2023-10-14 10:29:11 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
2023-10-14 10:29:11 at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
2023-10-14 10:29:11 at io.camunda.zeebe.spring.client.bean.MethodInfo.invoke(MethodInfo.java:51) ~[spring-client-zeebe-8.2.3.jar!/:8.2 .3]
2023-10-14 10:29:11 at io.camunda.zeebe.spring.client.jobhandling.JobHandlerInvokingSpringBeans.handle(JobHandlerInvokingSpringBeans.java:52) ~[spring-client-zeebe-8.2.3.jar!/:8.2 .3]
2023-10-14 10:29:11 at io.camunda.zeebe.client.impl.worker.JobRunnableFactory.executeJob(JobRunnableFactory.java:44) ~[zeebe-client-java-8.2.3.jar!/:8.2 .3]
2023-10-14 10:29:11 at io.camunda.zeebe.client.impl.worker.JobRunnableFactory.lambda$create$0(JobRunnableFactory.java:39) ~[zeebe-client-java-8.2.3.jar! /:8.2.3]
2023-10-14 10:29:11 at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
2023-10-14 10:29:11 at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
2023-10-14 10:29:11 at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
2023-10-14 10:29:11 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
2023-10-14 10:29:11 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
2023-10-14 10:29:11 at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
```

I'd like to know what's wrong.

**Comment by lwluc** [comment]
Hello there, @RodrigoCarlstrom,

We're thrilled to learn that you're making use of the CarbonReductor. 🙂

Quick question, though: Have you employed the token that you requested via https://api2.watttime.org/v2/login as your password within the environment variables in the docker-compose file?

Just to clarify, there's no need to create a token by yourself. The Carbon-Aware-SDK has that covered. What you should be doing is passing your complete credentials as environment variables, not a Bearer token.

Here's a little snippet to guide you:

```bash
$ docker run -it -p 8080:80 \
    -e DataSources__ForecastDataSource="WattTime" \
    -e DataSources__Configurations__WattTime__Type="WattTime" \
    -e DataSources__Configurations__WattTime__Username="wattTimeUsername" \
    -e DataSources__Configurations__WattTime__Password="wattTimePassword" \
  ghcr.io/green-software-foundation/carbon-aware-sdk
```

If you're curious about the nitty-gritty of the environment variables required, do check out the [Carbon-Aware-SDK docs](https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/docs/overview.md#run-web-api-container). They've got all the juicy details. 😊

**Comment by RodrigoCarlstrom** [comment]
Good morning Luc, Carbon Reduction is very interesting, we want to disseminate it in Brazil!

I really imagined that there would be no need to pass the token and that it would be enough to include the API username and password in docker-compose: [https://api2.watttime.org/v2/login](https://api2.watttime.org/v2/login)

doker-compose now looks like this:
```
version: "3.9"
services:

  carbon-aware-webapi:
    image: ghcr.io/green-software-foundation/carbon-aware-sdk
    container_name: carbon-aware-webapi
    environment:
      - DataSources__EmissionsDataSource=WattTime
      - DataSources__ForecastDataSource=WattTime
      - DataSources__Configurations__WattTime__Type=WattTime
      - DataSources__Configurations__WattTime__Username=********
      - DataSources__Configurations__WattTime__Password=********
    healthcheck:
      test: curl --fail 'http://localhost:80/emissions/forecasts/current?location=westus' || exit 1
      interval: 5s
      retries: 5
      start_period: 3s
      timeout: 2s
    ports:
      - "8090:80"

  camunda-8-carbon-reductor-connector:
    image: enviteconsulting/camunda-8-carbon-reductor-connector
    build:
      context: ../
      dockerfile: camunda-carbon-reductor-c8/Dockerfile
    container_name: camunda-8-carbon-reductor-connector
    depends_on:
      carbon-aware-webapi:
        condition: service_healthy
    environment:
      - CLIENT_ID=*********************************
      - CLUSTER_ID=*********************************
      - CLIENT_SECRET=*********************************
      - CLIENT_REGION=dsm-1
      # To enable or disable the Carbon Aware SDK usage
      - CARBON-REDUCTOR_CARBON-AWARE-API_ENABLED=true
      # To override the URL of the carbon api you could use the following variable
      - CARBON-REDUCTOR_CARBON-AWARE-API_BASE-PATH=http://carbon-aware-webapi:80
      # To enable or disable the Carbon Aware Computing API usage
      # - CARBON-REDUCTOR_CARBON-AWARE-COMPUTING_ENABLED=true
      # - CARBON-REDUCTOR_CARBON-AWARE-COMPUTING_API_KEY=<api-key>
    ports:
      - "8080:8080"
```


But I'm still encountering the same error:
`de.envite.greenbpm.api.carbonawaresdk.ApiException: Message: Forbidden`

**Comment by lwluc** [comment]
The idea of spreading carbon awareness in Brazil sounds intriguing. If you'd like some assistance, feel free to reach out to me, perhaps through [LinkedIn](https://www.linkedin.com/in/luc-weinbrecht/) or any other means that suits you best. I'd be more than happy to be of help! 😊

May I ask, in your Carbon Reductor configuration, which region do you currently employ? 
As of now, the only available option within the visitor plan of Watttime is `CAISO_NORTH`, which corresponds to our `westus` region. 
If you need more details, you can refer to the [Watttime Plans Docs](https://www.watttime.org/get-the-data/data-plans/). 

I believe this should resolve your issue. 😊

**Comment by RodrigoCarlstrom** [comment]
Yes, it works now!
![image](https://github.com/envite-consulting/camunda-carbon-reductor/assets/8772454/7f247dc3-b86f-4e22-868b-bb7339ab1229)

However, the reducer did not return the `carbonReduction` and `savedCarbonPercentage` variables to zero.
![image](https://github.com/envite-consulting/camunda-carbon-reductor/assets/8772454/eaeaddcc-b70e-48fd-8154-dd262f1328e1)

And the process didn't stop, it went straight on. Could this be due to the time of day?

**Comment by lwluc** [comment]
Wonderful! I'm delighted to hear that everything is working smoothly for you now. 🙂

It seems that your configuration might have left no better options. The timing could be influenced by the time of day. If you have any questions or need further assistance, please don't hesitate to ask.

**Comment by RodrigoCarlstrom** [comment]
Thanks Luc!
